#!/usr/bin/env bash
# This script replaces the content of /etc/nginx/sites-enabled/temp_redirect
# with a valid Nginx server block configuration and restarts the Nginx service

cat > /etc/nginx/sites-enabled/temp_redirect <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Other server configurations can be added here if needed

}
EOF

service nginx stop
service nginx start

