#!/usr/bin/env bash
# 101-manage_my_process

PID_FILE="/var/run/my_process.pid"

start_process() {
  sudo ./manage_my_process &
  echo $! > "$PID_FILE"
  echo "manage_my_process started"
}

stop_process() {
  if [ -e "$PID_FILE" ]; then
    pid=$(cat "$PID_FILE")
    sudo kill "$pid"
    rm -f "$PID_FILE"
    echo "manage_my_process stopped"
  else
    echo "No running process found"
  fi
}

restart_process() {
  stop_process
  start_process
  echo "manage_my_process restarted"
}

case "$1" in
  start)
    start_process
    ;;
  stop)
    stop_process
    ;;
  restart)
    restart_process
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

