#!/usr/bin/env bash
# This script kills the process 7-highlander.

# Find and get the process ID of 7-highlander
pid=$(pgrep -f "7-highlander")

if [ -n "$pid" ]; then
  # Send the SIGKILL signal to the process
  kill -s SIGKILL "$pid"
  echo "Killed"
else
  echo "Process not found"
fi

