#!/usr/bin/env bash
# This script displays information about users from the /etc/passwd file.
while IFS=: read -r username _ uid gid _ home shell _; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode x."
done < /etc/passwd
