#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

# Counter for hours
hour=0

# Using a while loop to iterate through hours
while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    
    # Counter for minutes
    minute=1

    # Using a while loop to iterate through minutes
    while [ $minute -le 59 ]; do
        echo "$minute"
        ((minute++))
    done
    
    ((hour++))
done

