#!/usr/bin/env bash
# This script configures localhost and facebook.com resolution

# Update /etc/hosts to change localhost IP
sudo sed -i 's/^127\.0\.0\.1.*/127.0.0.2 localhost/' /etc/hosts

# Update /etc/hosts to change facebook.com IP
sudo sed -i 's/^.*facebook\.com.*/8.8.8.8 facebook.com/' /etc/hosts

